// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7RoLf3rGQnSYcTOdvF35QFl0-MlO9_dk',
    appId: '1:879632283693:web:2846f9bb5e7aa9a7ca60a4',
    messagingSenderId: '879632283693',
    projectId: 'final-project-181fd',
    authDomain: 'final-project-181fd.firebaseapp.com',
    storageBucket: 'final-project-181fd.appspot.com',
    measurementId: 'G-K41BR3ZBK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxG_UbDiffDJsyLEvjYIehGDVJKanfGpg',
    appId: '1:879632283693:android:cb04aaa4ff949027ca60a4',
    messagingSenderId: '879632283693',
    projectId: 'final-project-181fd',
    storageBucket: 'final-project-181fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOAyJlJPevlhcjqz6bIkXBzuuHNcY1lPw',
    appId: '1:879632283693:ios:be6ae9a935017ce9ca60a4',
    messagingSenderId: '879632283693',
    projectId: 'final-project-181fd',
    storageBucket: 'final-project-181fd.appspot.com',
    iosBundleId: 'com.example.finalProjectPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOAyJlJPevlhcjqz6bIkXBzuuHNcY1lPw',
    appId: '1:879632283693:ios:be6ae9a935017ce9ca60a4',
    messagingSenderId: '879632283693',
    projectId: 'final-project-181fd',
    storageBucket: 'final-project-181fd.appspot.com',
    iosBundleId: 'com.example.finalProjectPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7RoLf3rGQnSYcTOdvF35QFl0-MlO9_dk',
    appId: '1:879632283693:web:64a7b9f903ed0f8aca60a4',
    messagingSenderId: '879632283693',
    projectId: 'final-project-181fd',
    authDomain: 'final-project-181fd.firebaseapp.com',
    storageBucket: 'final-project-181fd.appspot.com',
    measurementId: 'G-WVB19623WE',
  );
}
